<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BYODIIcU3lIgowY" failures="1" tests="1" name="Multis_Order_1" time="0.089" errors="0" timestamp="2023-07-24T22:47:30 IST">
  <testcase classname="com.WMS_Utilities.WMS_TestBase" name="@AfterTest tearDown" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.WebDriver.quit()&amp;quot; because &amp;quot;this.driver&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "this.driver" is null
at com.WMS_Utilities.WMS_TestBase.tearDown(WMS_TestBase.java:337)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="com.WMS_Utilities.WMS_TestBase" name="@AfterTest tearDown" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.WebDriver.quit()&amp;quot; because &amp;quot;this.driver&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "this.driver" is null
at com.WMS_Utilities.WMS_TestBase.tearDown(WMS_TestBase.java:337)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="WMS_Mult_Ord_Batch_4.WMS_Multi_Gift_Card" name="orderAllocation" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss &amp;amp; Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss & Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss & Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at resources.DataProviders.Multibags_GiftCard(DataProviders.java:706)
... 19 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- orderAllocation -->
</testsuite> <!-- Multis_Order_1 -->
